export const SURFACES = Object.freeze({
  SHIPPER: 'shipper',
  COMPANY_X: 'company_x',
  COMPANY_Y: 'company_y',
  DRIVER: 'driver',
  AGENT_Z: 'agent_z',
  ADMIN: 'admin'
});

export const ROLES = Object.freeze({
  SUPER_ADMIN: 'super_admin',
  MARKETPLACE_ADMIN: 'marketplace_admin',
  CONFLICT_OFFICER: 'conflict_officer',
  SECURITY_ADMIN: 'security_admin',
  COMPLIANCE_OFFICER: 'compliance_officer',
  RISK_MANAGER: 'risk_manager',
  CUSTOMER_SUPPORT: 'customer_support',
  FINANCE_ADMIN: 'finance_admin',
  COMPANY_X_OWNER: 'company_x_owner',
  COMPANY_X_OPERATIONS_MANAGER: 'company_x_operations_manager',
  COMPANY_X_PRICING_EXPERT: 'company_x_pricing_expert',
  COMPANY_X_DISPATCHER: 'company_x_dispatcher',
  COMPANY_X_DOCUMENT_EXPERT: 'company_x_document_expert',
  COMPANY_Y_OWNER: 'company_y_owner',
  COMPANY_Y_DOCUMENT_ISSUER: 'company_y_document_issuer',
  DRIVER: 'driver',
  VEHICLE_OWNER: 'vehicle_owner',
  FLEET_PARTNER: 'fleet_partner',
  SHIPPER_ADMIN: 'shipper_admin',
  SHIPPER_LOGISTICS_USER: 'shipper_logistics_user',
  SHIPPER_FINANCE_USER: 'shipper_finance_user',
  CONSIGNEE: 'consignee',
  AGENT_Z: 'agent_z',
  CUSTOMS_BROKER: 'customs_broker',
  INSURANCE_USER: 'insurance_user',
  WAREHOUSE_TERMINAL_USER: 'warehouse_terminal_user',
  GOVERNMENT_OBSERVER: 'government_observer',
  CRM_ADMIN: 'crm_admin',
  SALES_MANAGER: 'sales_manager',
  SALES_REP: 'sales_rep',
  SDR: 'sdr',
  SUPPORT_AGENT: 'support_agent',
  SUPPORT_LEAD: 'support_lead',
  MARKETING_MANAGER: 'marketing_manager',
  CAMPAIGN_OPERATOR: 'campaign_operator',
  LOYALTY_MANAGER: 'loyalty_manager',
  PARTNER_SUCCESS: 'partner_success',
  DATA_GOVERNANCE_OFFICER: 'data_governance_officer'
});

export const ADMIN_ROLES = Object.freeze([
  ROLES.SUPER_ADMIN,
  ROLES.MARKETPLACE_ADMIN,
  ROLES.CONFLICT_OFFICER,
  ROLES.SECURITY_ADMIN,
  ROLES.COMPLIANCE_OFFICER,
  ROLES.RISK_MANAGER,
  ROLES.CUSTOMER_SUPPORT,
  ROLES.FINANCE_ADMIN,
  ROLES.GOVERNMENT_OBSERVER,
  ROLES.DATA_GOVERNANCE_OFFICER,
  ROLES.CRM_ADMIN,
  ROLES.SUPPORT_LEAD
]);

export const PERMISSIONS = Object.freeze({
  OWNER: 'O',
  CREATE: 'C',
  READ: 'R',
  UPDATE: 'U',
  APPROVE: 'A',
  CANCEL: 'X',
  EXPORT: 'EXP',
  PRINT: 'PRT',
  DOWNLOAD: 'DLD',
  SHARE: 'SHR',
  SEE_PRICE: 'P$',
  SEE_DOCUMENTS: 'D$',
  SEE_CONTACT: 'C$',
  SEE_LOCATION: 'L$',
  SEE_SETTLEMENT: 'S$',
  SEE_AUDIT: 'A$',
  CONTACT_REVEAL: 'RV$',
  EXPORT_REQUEST: 'EX$',
  SEND_CAMPAIGN: 'CM$'
});

export const DOMAIN_STATES = Object.freeze({
  commercial: ['DRAFT', 'RFQ_OPEN', 'OFFERS_RECEIVED', 'PROVIDER_AWARDED', 'CUSTOMER_CONTRACTED'],
  capacity: ['CAPACITY_RFQ', 'ELIGIBLE', 'CARRIER_AWARDED', 'TRUCK_NOMINATED', 'CHECKED_IN'],
  loading: ['PRELOAD_ACCEPTED', 'LOADED', 'WEIGHT_CONFIRMED', 'COMMERCIAL_DOCS_READY'],
  customs: ['DECLARED', 'ASSESSED', 'EXPORT_PERMIT', 'SEALED', 'NO_SEAL_AUTHORIZED', 'EXIT_CONFIRMED'],
  tir: ['NOT_APPLICABLE', 'CARNET_ISSUED', 'OPENED', 'CHECKPOINTS', 'DISCHARGED'],
  trip: ['DISPATCHED', 'AT_BORDER', 'EXITED_IRAN', 'IN_TRANSIT', 'AT_DESTINATION', 'READY_FOR_DELIVERY'],
  delivery: ['DELIVERED', 'POD_SUBMITTED', 'POD_ACCEPTED'],
  financial: ['SETTLEMENT_PENDING', 'FINANCIALLY_SETTLED', 'CLOSED'],
  import: ['I01_IMPORT_REQUEST', 'I02_IMPORTER_VERIFICATION', 'I03_ORIGIN_ABROAD', 'I04_RFQ_PUBLISHED', 'I05_COMPANY_X_SELECTED', 'I06_OPERATIONAL_DISPATCH', 'I07_LOADING_ABROAD', 'I08_CMR_TIR_ACTIVE', 'I09_ENTRY_BORDER_EVENT', 'I10_DOCUMENT_HOLD', 'I11_CUSTOMS_WAREHOUSE_RELEASE', 'I12_DOMESTIC_DELIVERY', 'I13_SETTLEMENT', 'I14_CLOSE_DISPUTE']
});

export const RFQ_LEVELS = Object.freeze({ MARKET_A: 'RFQ1', MARKET_B: 'RFQ2' });

export const RFQ_STATES = Object.freeze(['OPEN', 'AWARDED', 'CANCELLED', 'EXPIRED']);

export const EVENTS = Object.freeze([
  'CargoRequestCreated',
  'CargoRequestUpdated',
  'RFQPublished',
  'QuoteSubmitted',
  'OffersWindowClosed',
  'ProviderAwarded',
  'AwardAccepted',
  'ContractSigned',
  'ContractAmended',
  'CustomerContracted',
  'OperationalRFQPublished',
  'LoadingScheduleCreated',
  'DriverBidSubmitted',
  'CarrierAwarded',
  'VehicleIntroduced',
  'TruckNominated',
  'AgentDeviceBound',
  'AgentAssignmentCreated',
  'AgentDeliveryVerified',
  'DeliveryEvidenceSubmitted',
  'DriverDeviceBound',
  'DriverDocumentSubmitted',
  'DriverTripAccepted',
  'CheckInRecorded',
  'PreloadChecklistSubmitted',
  'LoadingEvidenceSubmitted',
  'LoadingCompleted',
  'WeightConfirmed',
  'CustomsDeclared',
  'ExportPermitGranted',
  'CMRDraftCreated',
  'CMRDraftApproved',
  'CMRDraftRejected',
  'CMRIssued',
  'TIRIssued',
  'TIROpened',
  'TIRStateChanged',
  'TIRDischarged',
  'TripStarted',
  'GPSInterrupted',
  'RouteDeviationDetected',
  'GPSAnomalyDetected',
  'BorderEventRecorded',
  'DestinationArrived',
  'DeliveryOtpRequested',
  'DeliveryOtpVerified',
  'IncidentReported',
  'DriverAvailabilityChanged',
  'PODSubmitted',
  'PODReturned',
  'PODAccepted',
  'SettlementRequested',
  'SettlementConfirmed',
  'PaymentConfirmed',
  'ClaimOpened',
  'ClaimUpdated',
  'DisputeOpened',
  'ComplianceBlocked',
  'FraudFlagged',
  'RiskFlagged',
  'ExceptionOpened',
  'ExceptionUpdated',
  'ClaimEvidenceAdded',
  'DisputeUpdated',
  'NotificationSent',
  'ContactRevealed',
  'ImportRequestCreated',
  'WarehouseReceiptRecorded',
  'CommunicationConsentCaptured',
  'ExportRequested',
  'ExportApproved',
  'ExportExecuted',
  'QualificationDecisionRecorded',
  'BreakGlassRequested',
  'BreakGlassApproved',
  'BreakGlassRevoked',
  'RulePackStateChanged',
  'ConflictCaseUpdated',
  'SecurityIncidentOpened',
  'NotificationPolicyChanged',
  'AIReviewRecorded'
]);

export const ERROR_CODES = Object.freeze({
  STEP_UP_REQUIRED: 'AUTH-428',
  QUALIFICATION_EXPIRED: 'QUA-423',
  CARRIER_COVERAGE_MISSING: 'COV-424',
  VEHICLE_CARGO_MISMATCH: 'VEH-422',
  INELIGIBLE_CAPACITY: 'CAP-422',
  BID_OUTSIDE_WINDOW: 'BID-409',
  FORBIDDEN_DIRECT_DRIVER_AWARD: 'AWD-403',
  COMPLIANCE_BLOCK: 'CMP-451',
  DOCUMENT_LOCKED: 'DOC-423',
  INCOMPLETE_POD: 'POD-424',
  TIR_UNAUTHORIZED_HOLDER: 'TIR-424',
  OTP_EXPIRED: 'OTP-424',
  DRIVER_DEVICE_REQUIRED: 'DEVICE-403',
  GPS_ANOMALY: 'GPS-422',
  AGENT_ASSIGNMENT_MISSING: 'AGT-403',
  AGENT_NOT_VERIFIED: 'AGT-423',
  AUTHORITY_EXPIRED: 'AGT-424',
  RECIPIENT_MISMATCH: 'AGT-422',
  LOCATION_MISMATCH: 'GEO-422',
  SETTLEMENT_CONDITION_MISSING: 'FIN-424',
  CLAIM_TIMING_WARNING: 'CLM-408',
  FINANCIAL_DISPUTE_LOCK: 'DSP-423',
  CRM_SCOPE: 'CRM-403',
  CONTACT_REVEAL_CAP: 'CRM-429',
  CONSENT_MISSING: 'CRM-424',
  ADMIN_PERMISSION: 'ADM-403',
  RULEPACK_INVALID: 'RULE-422',
  RULEPACK_STATE: 'RULE-409',
  CRITICAL_NOTIFICATION: 'NTF-403',
  WEBHOOK_REPLAY: 'INT-409'
});

export const RELATIONSHIPS = Object.freeze({
  CUSTOMER_X: 'customer_x',
  X_Y: 'x_y',
  Y_DRIVER: 'y_driver',
  X_AGENT: 'x_agent',
  PLATFORM_FEE: 'platform_fee',
  CREDITS_ADJUSTMENTS: 'credits_adjustments'
});

export const ROLE_PERMISSIONS = Object.freeze({
  super_admin: [PERMISSIONS.READ, PERMISSIONS.CREATE, PERMISSIONS.UPDATE, PERMISSIONS.APPROVE, PERMISSIONS.SEE_AUDIT],
  marketplace_admin: [PERMISSIONS.READ, PERMISSIONS.CREATE, PERMISSIONS.UPDATE, PERMISSIONS.APPROVE, PERMISSIONS.SEE_AUDIT],
  conflict_officer: [PERMISSIONS.READ, PERMISSIONS.CREATE, PERMISSIONS.UPDATE, PERMISSIONS.APPROVE, PERMISSIONS.SEE_AUDIT],
  security_admin: [PERMISSIONS.READ, PERMISSIONS.CREATE, PERMISSIONS.UPDATE, PERMISSIONS.APPROVE, PERMISSIONS.SEE_AUDIT],
  compliance_officer: [PERMISSIONS.READ, PERMISSIONS.CREATE, PERMISSIONS.UPDATE, PERMISSIONS.APPROVE, PERMISSIONS.SEE_DOCUMENTS, PERMISSIONS.SEE_AUDIT],
  risk_manager: [PERMISSIONS.READ, PERMISSIONS.CREATE, PERMISSIONS.UPDATE, PERMISSIONS.APPROVE, PERMISSIONS.SEE_LOCATION, PERMISSIONS.SEE_AUDIT],
  customer_support: [PERMISSIONS.READ, PERMISSIONS.CREATE, PERMISSIONS.UPDATE, PERMISSIONS.SEE_CONTACT],
  finance_admin: [PERMISSIONS.READ, PERMISSIONS.CREATE, PERMISSIONS.UPDATE, PERMISSIONS.APPROVE, PERMISSIONS.SEE_SETTLEMENT, PERMISSIONS.SEE_AUDIT],
  company_x_owner: [PERMISSIONS.OWNER, PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.APPROVE, PERMISSIONS.DOWNLOAD, PERMISSIONS.SEE_PRICE, PERMISSIONS.SEE_DOCUMENTS, PERMISSIONS.SEE_CONTACT, PERMISSIONS.SEE_LOCATION, PERMISSIONS.SEE_SETTLEMENT, PERMISSIONS.SEE_AUDIT],
  company_x_operations_manager: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.APPROVE, PERMISSIONS.DOWNLOAD, PERMISSIONS.SEE_DOCUMENTS, PERMISSIONS.SEE_CONTACT, PERMISSIONS.CONTACT_REVEAL, PERMISSIONS.SEE_LOCATION, PERMISSIONS.SEE_SETTLEMENT],
  company_x_pricing_expert: [PERMISSIONS.READ, PERMISSIONS.CREATE, PERMISSIONS.UPDATE, PERMISSIONS.SEE_PRICE],
  company_x_dispatcher: [PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.CREATE, PERMISSIONS.DOWNLOAD, PERMISSIONS.SEE_DOCUMENTS, PERMISSIONS.SEE_CONTACT, PERMISSIONS.CONTACT_REVEAL, PERMISSIONS.SEE_LOCATION],
  company_x_document_expert: [PERMISSIONS.READ, PERMISSIONS.CREATE, PERMISSIONS.UPDATE, PERMISSIONS.APPROVE, PERMISSIONS.SEE_DOCUMENTS, PERMISSIONS.DOWNLOAD],
  company_y_owner: [PERMISSIONS.OWNER, PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.APPROVE, PERMISSIONS.DOWNLOAD, PERMISSIONS.SEE_DOCUMENTS, PERMISSIONS.SEE_CONTACT, PERMISSIONS.SEE_LOCATION, PERMISSIONS.SEE_SETTLEMENT],
  company_y_document_issuer: [PERMISSIONS.READ, PERMISSIONS.CREATE, PERMISSIONS.UPDATE, PERMISSIONS.APPROVE, PERMISSIONS.SEE_DOCUMENTS, PERMISSIONS.DOWNLOAD],
  driver: [PERMISSIONS.OWNER, PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DOWNLOAD, PERMISSIONS.SEE_DOCUMENTS, PERMISSIONS.SEE_LOCATION],
  vehicle_owner: [PERMISSIONS.OWNER, PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.SEE_DOCUMENTS],
  fleet_partner: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.SEE_DOCUMENTS],
  shipper_admin: [PERMISSIONS.OWNER, PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.APPROVE, PERMISSIONS.CANCEL, PERMISSIONS.EXPORT, PERMISSIONS.PRINT, PERMISSIONS.DOWNLOAD, PERMISSIONS.SHARE, PERMISSIONS.SEE_PRICE, PERMISSIONS.SEE_DOCUMENTS, PERMISSIONS.SEE_CONTACT, PERMISSIONS.SEE_LOCATION, PERMISSIONS.SEE_SETTLEMENT, PERMISSIONS.SEE_AUDIT],
  shipper_logistics_user: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.APPROVE, PERMISSIONS.DOWNLOAD, PERMISSIONS.SEE_DOCUMENTS, PERMISSIONS.SEE_CONTACT, PERMISSIONS.SEE_LOCATION],
  shipper_finance_user: [PERMISSIONS.READ, PERMISSIONS.APPROVE, PERMISSIONS.SEE_PRICE, PERMISSIONS.SEE_SETTLEMENT, PERMISSIONS.SEE_AUDIT],
  consignee: [PERMISSIONS.READ, PERMISSIONS.SEE_DOCUMENTS, PERMISSIONS.SEE_LOCATION],
  agent_z: [PERMISSIONS.OWNER, PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DOWNLOAD, PERMISSIONS.SEE_DOCUMENTS, PERMISSIONS.SEE_LOCATION, PERMISSIONS.SEE_SETTLEMENT],
  customs_broker: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.APPROVE, PERMISSIONS.SEE_DOCUMENTS, PERMISSIONS.DOWNLOAD],
  insurance_user: [PERMISSIONS.READ, PERMISSIONS.CREATE, PERMISSIONS.SEE_DOCUMENTS],
  warehouse_terminal_user: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.SEE_DOCUMENTS, PERMISSIONS.SEE_LOCATION],
  government_observer: [PERMISSIONS.READ, PERMISSIONS.SEE_DOCUMENTS, PERMISSIONS.SEE_AUDIT],
  crm_admin: [PERMISSIONS.OWNER, PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.APPROVE, PERMISSIONS.EXPORT_REQUEST, PERMISSIONS.CONTACT_REVEAL, PERMISSIONS.SEE_AUDIT],
  sales_manager: [PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.CONTACT_REVEAL, PERMISSIONS.EXPORT_REQUEST],
  sales_rep: [PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.CONTACT_REVEAL],
  sdr: [PERMISSIONS.READ, PERMISSIONS.UPDATE],
  support_agent: [PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.CONTACT_REVEAL],
  support_lead: [PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.CONTACT_REVEAL, PERMISSIONS.EXPORT_REQUEST],
  marketing_manager: [PERMISSIONS.READ, PERMISSIONS.EXPORT_REQUEST, PERMISSIONS.SEND_CAMPAIGN],
  campaign_operator: [PERMISSIONS.READ, PERMISSIONS.SEND_CAMPAIGN],
  loyalty_manager: [PERMISSIONS.READ, PERMISSIONS.UPDATE],
  partner_success: [PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.CONTACT_REVEAL],
  data_governance_officer: [PERMISSIONS.READ, PERMISSIONS.APPROVE, PERMISSIONS.EXPORT_REQUEST, PERMISSIONS.SEE_AUDIT]
});

export const STATE_GRAPH = Object.freeze({
  commercial: Object.freeze({ DRAFT: ['RFQ_OPEN'], RFQ_OPEN: ['OFFERS_RECEIVED', 'DRAFT'], OFFERS_RECEIVED: ['PROVIDER_AWARDED'], PROVIDER_AWARDED: ['CUSTOMER_CONTRACTED'] }),
  capacity: Object.freeze({ CAPACITY_RFQ: ['ELIGIBLE', 'CANCELLED'], ELIGIBLE: ['CARRIER_AWARDED'], CARRIER_AWARDED: ['TRUCK_NOMINATED'], TRUCK_NOMINATED: ['CHECKED_IN'] }),
  loading: Object.freeze({ PRELOAD_ACCEPTED: ['LOADED'], LOADED: ['WEIGHT_CONFIRMED'], WEIGHT_CONFIRMED: ['COMMERCIAL_DOCS_READY'] }),
  customs: Object.freeze({ DECLARED: ['ASSESSED'], ASSESSED: ['EXPORT_PERMIT'], EXPORT_PERMIT: ['SEALED', 'NO_SEAL_AUTHORIZED'], SEALED: ['EXIT_CONFIRMED'], NO_SEAL_AUTHORIZED: ['EXIT_CONFIRMED'] }),
  tir: Object.freeze({ CARNET_ISSUED: ['OPENED'], OPENED: ['CHECKPOINTS'], CHECKPOINTS: ['DISCHARGED'] }),
  trip: Object.freeze({ DISPATCHED: ['AT_BORDER'], AT_BORDER: ['EXITED_IRAN'], EXITED_IRAN: ['IN_TRANSIT'], IN_TRANSIT: ['AT_DESTINATION'], AT_DESTINATION: ['READY_FOR_DELIVERY'] }),
  delivery: Object.freeze({ DELIVERED: ['POD_SUBMITTED'], POD_SUBMITTED: ['POD_ACCEPTED'] }),
  financial: Object.freeze({ SETTLEMENT_PENDING: ['FINANCIALLY_SETTLED'], FINANCIALLY_SETTLED: ['CLOSED'] })
});

export function normalizeRole(value) {
  const role = String(value || '').trim().toLowerCase().replace(/[-\s]+/g, '_');
  return role === 'carrier' ? ROLES.COMPANY_Y_OWNER : role;
}

export function hasPermission(role, permission) {
  return (ROLE_PERMISSIONS[normalizeRole(role)] || []).includes(permission);
}

export function isCanonicalRole(role) {
  return Object.values(ROLES).includes(normalizeRole(role));
}

export function isHumanAwardRole(role, level) {
  const normalized = normalizeRole(role);
  if (level === RFQ_LEVELS.MARKET_A) return [ROLES.SHIPPER_ADMIN, ROLES.SHIPPER_LOGISTICS_USER].includes(normalized);
  if (level === RFQ_LEVELS.MARKET_B) return [ROLES.COMPANY_X_OWNER, ROLES.COMPANY_X_OPERATIONS_MANAGER].includes(normalized);
  return false;
}

export function eventNameIsKnown(eventName) {
  return EVENTS.includes(eventName);
}
